Repository Project-Lavinia/Lavinia-client, pull requests merged in 2020-08, with the labels that each got.

#205 Implement bulma-switch
  package.json
  src/Layout/ComputationMenu/AutoComputeCheckbox.tsx
  src/Layout/PresentationMenu/PresentationSettings/ComparisonCheckbox.tsx
  src/Layout/PresentationMenu/PresentationSettings/FiltersCheckbox.tsx
  src/Layout/PresentationMenu/PresentationSettings/MergeDistrictsCheckbox.tsx
  src/Layout/PresentationMenu/PresentationSettings/NoSeatsCheckbox.tsx
  src/Layout/PresentationMenu/PresentationSettings/Use2021DistributionCheckbox.tsx
  src/blue-theme.scss
  yarn.lock
Labels: dependencies, enhancement, style

#212 fix: disable clearing of local storage
  .gitignore
  cypress/integration/computation_menu.spec.ts
  cypress/integration/computation_modern_combinations_pt1.spec.ts
  cypress/integration/computation_modern_combinations_pt2.spec.ts
  cypress/integration/computation_old_combinations.spec.ts
  cypress/support/index.d.ts
  cypress/support/index.ts
  package.json
  src/utilities/api-requests.ts
  yarn.lock
Labels: continuous integration, dependencies, enhancement, fix, quality of life, refactor, testing

#221 refactor: Migrate from API v1
  .env.defaults
  cypress.json
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/Layout/ComputationMenu/ConnectedComputationMenu.tsx
  src/Layout/ComputationMenu/computation-menu-actions.ts
  src/Layout/ConnectedLayout.tsx
  src/Layout/Presentation/presentation-utilities.ts
  src/Layout/PresentationMenu/PresentationSettings/ConnectedPresentationSettings.tsx
  src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx
  src/computation/computation-actions.ts
  src/computation/computation-models.ts
  src/computation/computation-reducer.ts
  src/computation/computation-state.ts
  src/computation/logic/algorithm-utilities.ts
  src/computation/logic/distribute-levelling-seats.ts
  src/computation/logic/distribution.ts
  src/computation/logic/district-merging.ts
  src/computation/logic/execute-algorithm.ts
  src/computation/logic/lague-dhondt.ts
  src/computation/logic/quotient-dictionary.ts
  src/computation/logic/utils.ts
  src/requested-data/requested-data-actions.ts
  src/requested-data/requested-data-models.ts
  src/requested-data/requested-data-reducer.ts
  src/requested-data/requested-data-state.ts
  src/utilities/dictionary.ts
  src/utilities/map.ts
  src/utilities/number.ts
Labels: enhancement, migrate, minor version bump, refactor

#207 Small ui fixes
  cypress/integration/computation_menu.spec.ts
  cypress/integration/computation_modern_combinations_pt1.spec.ts
  cypress/integration/computation_modern_combinations_pt2.spec.ts
  cypress/integration/computation_old_combinations.spec.ts
  src/Layout/ComputationMenu/ResetButton.tsx
  src/Layout/ConnectedLayout.tsx
  src/Layout/Layout.tsx
  src/Layout/Presentation/ConnectedPresentation.tsx
  src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx
  src/Layout/Presentation/DistrictOverview/VulnerableDistrictSeatText.tsx
  src/Layout/Presentation/Presentation.tsx
  src/Layout/Presentation/RemainderQuotients/RemainderQuotients.tsx
  src/Layout/Presentation/SingleDistrict/InfoBox.tsx
  src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
  src/Layout/PresentationMenu/PresentationSettings/NoSeatsCheckbox.tsx
  src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx
  src/Layout/Tutorial/ConnectedTutorial.tsx
  src/Layout/Tutorial/Tutorial.tsx
  src/Layout/Tutorial/index.ts
  src/Layout/ui-reducer.ts
  src/assets/index.html
  src/blue-theme.scss
  src/common/PartyName/PartyName.tsx
  src/common/PartyName/index.ts
  src/requested-data/requested-data-actions.ts
  src/requested-data/requested-data-reducer.ts
Labels: enhancement, feature, fix, minor version bump, quality of life, refactor, style

#223 feat: catch and recover from errors
  src/Layout/ComputationMenu/computation-menu-actions.ts
  src/Layout/ComputationMenu/computation-menu-reducer.ts
  src/Layout/ConnectedLayout.tsx
  src/Layout/Layout.tsx
  src/Layout/Navigation/ConnectedNavigation.ts
  src/Layout/Notifications/ConnectedNotificationDisplay.tsx
  src/Layout/Notifications/Notification.tsx
  src/Layout/Notifications/NotificationDisplay.tsx
  src/Layout/Notifications/index.ts
  src/Layout/Notifications/notification-models.ts
  src/Layout/PresentationMenu/presentation-menu-actions.ts
  src/Layout/PresentationMenu/presentation-menu-reducer.ts
  src/Layout/Tutorial/ConnectedTutorial.tsx
  src/Layout/ui-actions.ts
  src/Layout/ui-reducer.ts
  src/Layout/ui-state.ts
  src/blue-theme.scss
  src/computation/computation-actions.ts
  src/computation/computation-reducer.ts
  src/reducers/global-actions.ts
  src/reducers/state.ts
  src/requested-data/requested-data-actions.ts
  src/requested-data/requested-data-reducer.ts
  src/store/version.ts
  src/utilities/api-requests.ts
Labels: enhancement, feature, minor version bump, quality of life

#231 Feature/spring cleaning
  package.json
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/Layout/Layout.tsx
  src/Layout/Presentation/ConnectedPresentation.tsx
  src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx
  src/Layout/Presentation/DistrictOverview/VulnerableDistrictSeatText.tsx
  src/Layout/Presentation/Presentation.tsx
  src/Layout/Presentation/RemainderQuotients/RemainderQuotients.tsx
  src/Layout/Presentation/SingleDistrict/InfoBox.tsx
  src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
  src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx
  src/blue-theme.scss
  src/computation/logic/algorithm-utilities.ts
  src/computation/logic/distribute-levelling-seats.ts
  src/computation/logic/distribution.ts
  src/computation/logic/lague-dhondt.ts
  src/computation/logic/quotient-dictionary.ts
  src/computation/logic/sorted-reverse-dict.ts
  src/utilities/conditionals.ts
  src/utilities/data-filters.ts
  src/utilities/district.ts
Labels: dependencies, enhancement, feature, fix, quality of life, refactor

#250 Fix: hiding parties crashes single district
  cypress/integration/presentation_menu.spec.ts
  src/utilities/district.ts
Labels: fix, testing

#247 Sort Single District by Total Seats
  src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
Labels: enhancement, quality of life

#244 fix: do not show 0 should be ≠ 0 not > 0
  src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx
Labels: enhancement, fix

#246 Add timeout for toasts
  package.json
  src/Layout/ConnectedLayout.tsx
  src/Layout/Layout.tsx
  src/Layout/Notifications/ConnectedNotificationDisplay.tsx
  src/Layout/Notifications/Notification.tsx
  src/Layout/Notifications/NotificationDisplay.tsx
  src/Layout/Notifications/index.ts
  src/Layout/Notifications/notification-models.ts
  src/Layout/ui-actions.ts
  src/Layout/ui-reducer.ts
  src/Layout/ui-state.ts
  src/blue-theme.scss
  yarn.lock
Labels: enhancement, feature, minor version bump, refactor

#251 feat: make Gallagher default prop. index
  src/Layout/PresentationMenu/PresentationSettings/DisproportionalitySelect.tsx
  src/Layout/PresentationMenu/presentation-menu-state.ts
Labels: enhancement, feature

#249 Show diff on settings change
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/Layout/ComputationMenu/ConnectedComputationMenu.tsx
  src/Layout/ComputationMenu/computation-menu-actions.ts
  src/Layout/ComputationMenu/computation-menu-reducer.ts
  src/Layout/ComputationMenu/computation-menu-state.ts
  src/Layout/Presentation/ConnectedPresentation.tsx
  src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx
  src/Layout/Presentation/Presentation.tsx
  src/utilities/conditionals.ts
Labels: enhancement, feature, refactor

#248 Improve tutorial modal
  src/Layout/Tutorial/Tutorial.tsx
Labels: enhancement, feature

#233 Create Jenkins pipeline for CI/CD
  .gitignore
  Jenkinsfile
  package.json
  webpack.config.js
Labels: continuous deployment, continuous integration, enhancement

#245 feat: improve About Lavinia
  src/Layout/Navigation/Navigation.tsx
Labels: enhancement, feature

#200 Style change and new features for presentations
  src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx
  src/Layout/Presentation/DistrictOverview/VulnerableDistrictSeatText.tsx
  src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx
  src/Layout/Presentation/LevellingSeatOverview/LevellingSeatOverview.tsx
  src/Layout/Presentation/Presentation.tsx
  src/Layout/Presentation/RemainderQuotients/RemainderQuotients.tsx
  src/Layout/Presentation/SeatDistribution/SeatDistribution.tsx
  src/Layout/Presentation/SingleDistrict/InfoBox.tsx
  src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
  src/blue-theme.scss
  src/utilities/customNumberFormat.ts
Labels: blocking, enhancement, refactor, style
