Repository Project-Lavinia/Lavinia-client, pull requests merged in 2020-05, with the labels that each got.

#135 Fix bugs + a new feature
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx
  src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
  src/Layout/PresentationMenu/PresentationSettings/MergeDistrictsCheckbox.tsx
  src/common/SmartNumericInput/SmartNumericInput.tsx
  src/common/SmartNumericInputWithLabel/SmartNumericInputWithLabel.tsx
  src/common/SmartNumericInputWithLabel/index.ts
  src/common/index.ts
Labels: bug

#139 refactor: migrate to API 3.0.0
  .env.defaults
  src/Layout/ComputationMenu/ConnectedComputationMenu.tsx
  src/Layout/ComputationMenu/computation-menu-actions.ts
  src/Layout/ConnectedLayout.tsx
  src/computation/computation-state.ts
  src/requested-data/requested-data-models.ts
  src/requested-data/requested-data-utilities.ts
Labels: enhancement, refactor

#137 fix: do not distribute seats won by parties below the election threshold
  src/computation/logic/distribute-levelling-seats.ts
Labels: blocking, bug

#133 feature: Largest fraction
  README.md
  README.nob.md
  src/Layout/ComputationMenu/AlgorithmSelect.tsx
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/Layout/Presentation/ConnectedPresentation.tsx
  src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx
  src/Layout/Presentation/DistrictOverview/VulnerableDistrictSeatText.tsx
  src/Layout/Presentation/Presentation.tsx
  src/Layout/Presentation/RemainderQuotients/RemainderQuotients.tsx
  src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
  src/Layout/PresentationMenu/PresentationSelection/presentation-selection-utilities.ts
  src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx
  src/computation/computation-models.ts
  src/computation/logic/algorithm-utilities.ts
  src/computation/logic/distribute-levelling-seats.ts
  src/computation/logic/distribution.ts
  src/computation/logic/lague-dhondt.ts
  src/computation/logic/quotient-dictionary.ts
  src/computation/logic/sorted-reverse-dict.ts
  src/computation/logic/utils.ts
  src/utilities/conditionals.ts
Labels: docs, enhancement, feature

#143 feat: enable use of district data from 2021
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/Layout/ComputationMenu/ConnectedComputationMenu.tsx
  src/Layout/PresentationMenu/PresentationSettings/ConnectedPresentationSettings.tsx
  src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx
  src/Layout/PresentationMenu/PresentationSettings/Use2021DistributionCheckbox.tsx
  src/Layout/PresentationMenu/presentation-menu-actions.ts
  src/Layout/PresentationMenu/presentation-menu-reducer.ts
  src/Layout/PresentationMenu/presentation-menu-state.ts
  src/computation/computation-actions.ts
Labels: enhancement, feature

#147 fix: handle few district seats
  src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
  src/computation/logic/utils.ts
  src/utilities/district.ts
Labels: bug

#150 Set default showPartiesWithoutSeats true
  src/Layout/PresentationMenu/presentation-menu-actions.ts
  src/Layout/PresentationMenu/presentation-menu-state.ts
Labels: enhancement

#149 Add is-hidden-touch optional-prop to SmartNumericInput
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/common/SmartNumericInput/SmartNumericInput.tsx
  src/common/SmartNumericInputWithLabel/SmartNumericInputWithLabel.tsx
Labels: enhancement

#140 feat: Indicate winner row - SingleDistrict
  src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
  src/assets/index.html
Labels: enhancement, feature

#153 Release 2.7.0
  .env.defaults
  README.md
  README.nob.md
  package.json
  src/Layout/ComputationMenu/AlgorithmSelect.tsx
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/Layout/ComputationMenu/ConnectedComputationMenu.tsx
  src/Layout/ComputationMenu/computation-menu-actions.ts
  src/Layout/ComputationMenu/computation-menu-models.ts
  src/Layout/ComputationMenu/computation-menu-state.ts
  src/Layout/ConnectedLayout.tsx
  src/Layout/Presentation/ConnectedPresentation.tsx
  src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx
  src/Layout/Presentation/DistrictOverview/VulnerableDistrictSeatText.tsx
  src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx
  src/Layout/Presentation/Presentation.tsx
  src/Layout/Presentation/RemainderQuotients/RemainderQuotients.tsx
  src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
  src/Layout/PresentationMenu/PresentationSelection/presentation-selection-utilities.ts
  src/Layout/PresentationMenu/PresentationSettings/ConnectedPresentationSettings.tsx
  src/Layout/PresentationMenu/PresentationSettings/MergeDistrictsCheckbox.tsx
  src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx
  src/Layout/PresentationMenu/PresentationSettings/Use2021DistributionCheckbox.tsx
  src/Layout/PresentationMenu/presentation-menu-actions.ts
  src/Layout/PresentationMenu/presentation-menu-reducer.ts
  src/Layout/PresentationMenu/presentation-menu-state.ts
  src/assets/index.html
  src/common/SmartNumericInput/SmartNumericInput.tsx
  src/common/SmartNumericInputWithLabel/SmartNumericInputWithLabel.tsx
  src/common/SmartNumericInputWithLabel/index.ts
  src/common/TooltipInfo/TooltipInfo.tsx
  src/common/TooltipInfo/index.ts
  src/common/index.ts
  src/computation/computation-actions.ts
  src/computation/computation-models.ts
  src/computation/computation-state.ts
  src/computation/logic/algorithm-utilities.ts
  src/computation/logic/distribute-levelling-seats.ts
  src/computation/logic/distribution.ts
  src/computation/logic/lague-dhondt.ts
  src/computation/logic/quotient-dictionary.ts
  src/computation/logic/sorted-reverse-dict.ts
  src/computation/logic/utils.ts
  src/requested-data/requested-data-models.ts
  src/requested-data/requested-data-utilities.ts
  src/store/version.ts
  src/utilities/conditionals.ts
  src/utilities/district.ts
Labels: continuous integration, docs, documentation, enhancement, feature, fix, refactor

#152 Update dependencies
  package.json
  src/Layout/Navigation/Navigation.tsx
  types/custom.d.ts
  webpack.config.js
  yarn.lock
Labels: dependencies

#158 Release/2.7.1
  package.json
  src/Layout/Navigation/Navigation.tsx
  src/store/version.ts
  types/custom.d.ts
  webpack.config.js
  yarn.lock
Labels: dependencies, fix

#160 Fix LGTM alerts
  package.json
  src/Layout/Navigation/Navigation.tsx
  src/store/index.ts
  webpack.config.js
  yarn.lock
Labels: fix

#163 Release/2.7.2
  package.json
  src/Layout/Navigation/Navigation.tsx
  src/store/index.ts
  src/store/version.ts
  webpack.config.js
  yarn.lock
Labels: fix

#164 Configure webpack for scss
  package.json
  src/Layout/ComputationMenu/AlgorithmSelect.tsx
  src/Layout/ComputationMenu/AutoComputeCheckbox.tsx
  src/Layout/ComputationMenu/ComputeManuallyButton.tsx
  src/Layout/ComputationMenu/ResetButton.tsx
  src/Layout/ComputationMenu/ResetComparisonButton.tsx
  src/Layout/ComputationMenu/SaveComparisonButton.tsx
  src/Layout/ComputationMenu/YearSelect.tsx
  src/Layout/Navigation/LaviniaSVGLogo.tsx
  src/Layout/Navigation/Navigation.tsx
  src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx
  src/Layout/Presentation/DistrictOverview/VulnerableDistrictSeatText.tsx
  src/Layout/Presentation/RemainderQuotients/RemainderQuotients.tsx
  src/Layout/Presentation/SingleDistrict/DistrictSelect.tsx
  src/Layout/Presentation/SingleDistrict/InfoBox.tsx
  src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
  src/Layout/PresentationMenu/PresentationSettings/ComparisonCheckbox.tsx
  src/Layout/PresentationMenu/PresentationSettings/DisproportionalitySelect.tsx
  src/Layout/PresentationMenu/PresentationSettings/FiltersCheckbox.tsx
  src/Layout/PresentationMenu/PresentationSettings/MergeDistrictsCheckbox.tsx
  src/Layout/PresentationMenu/PresentationSettings/NoSeatsCheckbox.tsx
  src/Layout/PresentationMenu/PresentationSettings/Use2021DistributionCheckbox.tsx
  src/assets/index.html
  src/blue-theme.scss
  src/common/LaviniaSVGLogo/LaviniaSVGLogo.tsx
  src/common/LaviniaSVGLogo/index.ts
  src/common/SmartNumericInput/SmartNumericInput.tsx
  src/common/SmartNumericInputWithLabel/SmartNumericInputWithLabel.tsx
  src/common/TooltipInfo/TooltipInfo.tsx
  src/common/index.ts
  src/main.tsx
  src/utilities/rt.tsx
  webpack.config.js
  yarn.lock
Labels: enhancement, fix, help wanted, style

#177 fix: correct rounding of LF algorithms
  src/computation/logic/algorithm-utilities.ts
Labels: fix

#180 feat: implement page loader
  package.json
  src/Layout/ConnectedLayout.tsx
  src/Layout/Layout.tsx
  src/blue-theme.scss
  src/requested-data/requested-data-reducer.ts
  src/requested-data/requested-data-state.ts
  yarn.lock
Labels: enhancement, feature

#182 fix: handle display of 0 leveling seats
  src/Layout/Presentation/LevellingSeatOverview/LevellingSeatOverview.tsx
  src/utilities/rt.tsx
Labels: fix

#181 feature: hide show all parties when it is not relevant
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/Layout/PresentationMenu/PresentationSettings/NoSeatsCheckbox.tsx
  src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx
Labels: fix

#185 fix: handle compare when year changes
  src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx
Labels: fix

#186 feature: update readme
  README.md
  README.nob.md
Labels: docs, documentation, enhancement
