Repository Project-Lavinia/Lavinia-client, pull requests merged in 2020-02, with the labels that each got.

#75 Update dependencies (february 2020)
  package.json
  yarn.lock
Labels: dependencies

#76 Update dependencies
  package.json
  yarn.lock
Labels: fix

#78 Single district percent
  src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
Labels: enhancement, feature

#77 feat: Implemented threshold for district seats
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/Layout/ComputationMenu/ConnectedComputationMenu.tsx
  src/Layout/ComputationMenu/computation-menu-actions.ts
  src/Layout/ComputationMenu/computation-menu-models.ts
  src/Layout/ComputationMenu/computation-menu-reducer.ts
  src/Layout/ComputationMenu/computation-menu-state.ts
  src/computation/computation-actions.ts
  src/computation/computation-models.ts
  src/computation/computation-reducer.ts
  src/computation/computation-state.ts
  src/computation/logic/algorithm-utilities.ts
  src/computation/logic/distribute-levelling-seats.ts
  src/computation/logic/lague-dhondt.ts
Labels: enhancement, feature
