Repository Project-Lavinia/Lavinia-client, pull requests merged in 2020-09, with the labels that each got.

#258 feat: only run tests when creating release
  Jenkinsfile
  package.json
Labels: enhancement

#262 fix: correct tutorial typo
  src/Layout/Tutorial/Tutorial.tsx
Labels: fix

#259 fix: keep tooltip from clipping
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
  src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx
  src/common/TooltipInfo/TooltipInfo.tsx
  src/common/TooltipInfo/TooltipInfoRight.tsx
  src/common/TooltipInfo/index.ts
Labels: fix, style

#260 Add dynamic content to tooltipinfo in presentation selection
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
Labels: enhancement, feature, fix

#264 2.9.2
  package.json
  src/Layout/ComputationMenu/ComputationMenu.tsx
  src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
  src/store/version.ts
Labels: enhancement, feature, fix, quality of life
